schema_version = "1.0.0"
id = "bl_ext_test"
name = "** from bl_info **"
version = "** from bl_info **"
tagline = "** from bl_info **"
maintainer = "** from bl_info **"
type = "add-on"
tags = ["Import-Export"]
blender_version_min = "** from bl_info **"
blender_version_max = "5.1.99"
license = ["Apache-2.0"]
website = "https://github.com/mmt3d/bl-ext-test"
copyright = ["2026 mmt3d"]

[permissions]
files = "Imports images, nodes, and translations from the bundled files"
