name: Create Release Draft on Version Update

on:
  push:
    branches:
      - main
    paths:
      - 'bl-ext-test/__init__.py'

permissions:
  contents: write

jobs:
  create-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Extract Version from bl_info
        id: get_version
        run: python .github/scripts/get_version.py

      - name: Create GitHub Release Draft
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: v${{ steps.get_version.outputs.version }}
          draft: true
          body: |
            *
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}