name: Deploy Blender Extension

on:
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v6
#        with:
#          path: src
#
#      - name: Checkout Distribution Repository
#        uses: actions/checkout@v6
#        with:
#          repository: 'mmt3d/blender-extensions'
#          token: ${{ secrets.DEPLOY_TOKEN }}
#          path: dist
#
#      - name: Set up Python
#        uses: actions/setup-python@v6
#        with:
#          python-version: '3.13'
#
#      - name: Create Manifest
#        id: build_meta
#        run: python src/.github/scripts/create_manifest.py
#
#      - name: Zip extension folder
#        run: |
#          cd src/bl-ext-test
#          zip -r ../${{ steps.build_meta.outputs.zip_name }} ./*
#
#      - name: Create Metadata
#        env:
#          ZIP_NAME: ${{ steps.build_meta.outputs.zip_name }}
#          TAG_NAME: ${{ github.event.release.tag_name }}
#        run: python src/.github/scripts/create_metadata.py
#
#      - name: Upload ZIP to GitHub Release
#        uses: softprops/action-gh-release@v3
#        with:
#          files: src/${{ steps.build_meta.outputs.zip_name }}
#          tag_name: ${{ github.event.release.tag_name }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Commit and Push to Central Repository
#        run: |
#          cd dist
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git add metadata/
#          if ! git diff --cached --exit-code; then
#            git commit -m "chore: Add version metadata for ${{ steps.build_meta.outputs.zip_name }}"
#            git push origin main
#          else
#            echo "既に配信リポジトリに存在します。"
#          fi
      - name: Restore Stocked Metadata from Cache
        uses: actions/cache/restore@v4
        with:
          path: metadata.json
          key: metadata-${{ github.event.repository.name }}-${{ github.event.release.tag_name }}-${{ github.event.release.id }}
          fail-on-cache-miss: true

      - name: Load metadata content
        id: load_json
        run: |
          JSON_CONTENT=$(jq -c . metadata.json)
          echo "meta_payload=${JSON_CONTENT}" >> $GITHUB_ENV

      - name: Send Signal to Distribution Repository
        run: |
          curl -L \
            X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
            https://api.github.com/repos/mmt3d/blender-extensions/dispatches \
            -d '{"event_type": "addon_published", "client_payload": {"metadata": ${{ env.meta_payload }}}}'
