name: Deploy Blender Extension

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.11'

      - name: Process Manifest and Update Central index.json
        id: build_meta
        run: |
          python .github/scripts/update_index.py

      - name: Create build directories
        run: |
          mkdir -p dist/zips
          # 更新された index.json を公開用フォルダにコピー
          cp index.json dist/

      - name: Zip extension folder
        run: |
          # bl-ext-test フォルダそのものではなく、中のファイル群をルートとして zip 圧縮する
          cd bl-ext-test && zip -r ../dist/zips/${{ steps.build_meta.outputs.zip_name }} ./*

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
