name: Test Output

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
#    outputs:
#      zip_name: ${{ steps.build_meta.outputs.zip_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          path: src

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Test Script
        id: build_meta
        run: python src/.github/scripts/update_index.py

      - name: Echo output
        run: |
          echo ${{ steps.build_meta.outputs.zip_name }}
